FirstDemo.Web/Areas/Admin/Controllers/CourseController.cs
using Autofac;
using FirstDemo.Infrastructure.Features.Exceptions;
using FirstDemo.Infrastructure.Models;
using FirstDemo.Web.Areas.Admin.Models;
using FirstDemo.Web.Models;
using FirstDemo.Web.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace FirstDemo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
	public class CourseController : Controller
	{
		ILifetimeScope _scope;
        ILogger<CourseController> _logger;


        public CourseController(ILifetimeScope scope, ILogger<CourseController> logger)
		{
			_scope = scope;
            _logger = logger;
        }

		public IActionResult Index()
		{
			var model = _scope.Resolve<CourseListModel>();

			return View(model);
		}

        public IActionResult Create()
        {
            var model = _scope.Resolve<CourseCreateModel>();

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Create(CourseCreateModel model)
        {
            model.ResolveDependency(_scope);

            if (ModelState.IsValid)
            {
                try
                {
                    model.CreateCourse();
                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = "Successfully added a new course.",
                        Type = ResponseTypes.Success
                    });
                    return RedirectToAction("Index");
                }
                catch(DuplicateNameException ex)
                {
                    _logger.LogError(ex, ex.Message);
                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = ex.Message,
                        Type = ResponseTypes.Danger
                    });
                }
                catch(Exception e)
                {
                    _logger.LogError(e, "Server Error");

                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = "There was a problem in creating course.",
                        Type = ResponseTypes.Danger
                    });
                }
            }
            
            return View(model);
        }

        public IActionResult Update(Guid id)
        {
            var model = _scope.Resolve<CourseUpdateModel>();
            model.Load(id);
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Update(CourseUpdateModel model)
        {
            model.ResolveDependency(_scope);

            if (ModelState.IsValid)
            {
                try
                {
                    model.UpdateCourse();

                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = "Successfully updated course.",
                        Type = ResponseTypes.Success
                    });

                    return RedirectToAction("Index");
                }
                catch (DuplicateNameException ex)
                {
                    _logger.LogError(ex, ex.Message);

                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = ex.Message,
                        Type = ResponseTypes.Danger
                    });
                }
                catch (Exception e)
                {
                    _logger.LogError(e, "Server Error");

                    TempData.Put<ResponseModel>("ResponseMessage", new ResponseModel
                    {
                        Message = "There was a problem in updating course.",
                        Type = ResponseTypes.Danger
                    });
                }
            }

            return View(model);
        }

        public IActionResult Delete(Guid id)
        {
            var model = _scope.Resolve<CourseListModel>();

            if (ModelState.IsValid)
            {
                try
                {
                    model.DeleteCourse(id);
                }
                catch (Exception e)
                {
                    _logger.LogError(e, "Server Error");
                }
            }

            return RedirectToAction("Index");
        }

        public async Task<JsonResult> GetCourses()
		{
            var dataTablesModel = new DataTablesAjaxRequestUtility(Request);
			var model = _scope.Resolve<CourseListModel>();

            var data = await model.GetPagedCoursesAsync(dataTablesModel);
            return Json(data);
        }
    }
}

FirstDemo.Web/Areas/Admin/Views/Course/Create.cshtml
@model CourseCreateModel
@{
    ViewData["Title"] = "Create Course";
}

<div class="container-fluid">
    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Create Course</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form role="form" asp-antiforgery="true" asp-action="Create"
                      asp-area="Admin" asp-controller="Course" method="post">
                    <div class="card-body">
                        <partial name="_ResponsePartial" />
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name"></label>
                            <input type="text" class="form-control" asp-for="Name" placeholder="Enter title">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Fees"></label>
                            <input type="text" class="form-control" asp-for="Fees" placeholder="Enter fees">
                            <span asp-validation-for="Fees" class="text-danger"></span>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->

        </div>
        <!--/.col (left) -->
    </div>
    <!-- /.row -->
</div><!-- /.container-fluid -->
@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

FirstDemo.Web/Areas/Admin/Views/Course/Index.cshtml
@model CourseListModel
@{
    ViewData["Title"] = "Index";
}

@section Styles
{
    <link rel="stylesheet" href="/adminlte3/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}

<section class="content">
    <div class="row">
    <div class="col-12">
        <!-- /.card -->
        <div class="card">
        <div class="card-header">
            <h3 class="card-title">DataTable with default features</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <partial name="_ResponsePartial" />
            <table id="courses" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Fees</th>
                <th style="width:150px">Actions</th>
            </tr>
            </thead>
            <tbody></tbody>
            <tfoot>
            <tr>
                <th>Name</th>
                <th>Fees</th>
                <th style="width:150px">Actions</th>
            </tr>
            </tfoot>
            </table>
            <partial name="_ModalPartial" />
        </div>
        <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
  
@section Scripts
{
    <!-- DataTables -->
    <script src="~/adminlte3/plugins/datatables/jquery.dataTables.js"></script>
    <script src="~/adminlte3/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>

    <!-- page script -->
    <script>
        $(function () {
            $('#courses').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": {
                    "url": "/Admin/Course/GetCourses",
                },
                "columnDefs": [
                    {
                        "orderable": false,
                        "targets": 2,
                        "render": function (data, type, row) {
                            return `<button type="submit" class="btn btn-info btn-sm" onclick="window.location.href='/admin/course/update/${data}'" value='${data}'>
                                                <i class="fas fa-pencil-alt">
                                                </i>
                                                Edit
                                            </button>
                                            <button type="submit" class="btn btn-danger btn-sm show-bs-modal" data-id='${data}' value='${data}'>
                                                <i class="fas fa-trash">
                                                </i>
                                                Delete
                                            </button>`;
                        }
                    }
                ]
            });

            $('#courses').on('click', '.show-bs-modal', function (event) {
                var id = $(this).data("id");
                var modal = $("#modal-default");
                modal.find('.modal-body p').text('Are you sure you want to delete this record?');
                $("#deleteId").val(id);
                $("#deleteForm").attr("action", "/admin/course/delete");
                modal.modal('show');
            });

            $("#deleteButton").click(function () {
                $("#deleteForm").submit();
            });
        });
    </script>
}

FirstDemo.Web/Areas/Admin/Views/Course/Update.cshtml
@model CourseUpdateModel
@{
    ViewData["Title"] = "Update Course";
}

<div class="container-fluid">
    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Update Course</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form role="form" asp-antiforgery="true" asp-action="Update"
                      asp-area="Admin" asp-controller="Course" method="post">
                    <input type="hidden" asp-for="Id" />
                    <div class="card-body">
                        <partial name="_ResponsePartial" />
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name"></label>
                            <input type="text" class="form-control" asp-for="Name" placeholder="Enter title">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Fees"></label>
                            <input type="text" class="form-control" asp-for="Fees" placeholder="Enter fees">
                            <span asp-validation-for="Fees" class="text-danger"></span>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->

        </div>
        <!--/.col (left) -->
    </div>
    <!-- /.row -->
</div><!-- /.container-fluid -->
@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}